name: Sync Forked Repo

on:
  push:
    branches:
      - master

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    env:
      ORIGINAL_REPO: vaibhhvv/original-repo-3
      FORKED_REPO: vaibhshah/forked-repo-3
      BRANCH: master

    steps:
      - name: Checkout original repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ORIGINAL_REPO }}
          ref: ${{ env.BRANCH }}
          path: upstream-repo
          fetch-depth: 0

      - name: Clone forked repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/${FORKED_REPO}.git fork-repo
          cd fork-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync from upstream
        run: |
          # Move into forked repo
          cd fork-repo

          # Save fork workflows
          mkdir -p ../fork-workflows
          cp -r .github/workflows ../fork-workflows || true

          # Add upstream and fetch
          git remote add upstream ../../upstream-repo
          git fetch upstream
          
          # Create new sync branch from upstream/master
          git checkout -B sync-fork upstream/${BRANCH}

          # Restore workflows from fork
          rm -rf .github/workflows
          cp -r ../fork-workflows .github/workflows || true

          git add .
          git diff --cached --quiet && echo "No changes to sync" && exit 0

          git commit -m "🔄 Sync from upstream $ORIGINAL_REPO:$BRANCH"
          git push -f origin sync-fork

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "🔄 Sync from upstream"
          title: "🔄 Sync from upstream"
          body: |
            Auto-generated PR to sync with upstream `${{ env.ORIGINAL_REPO }}`
          base: ${{ env.BRANCH }}
          branch: sync-fork
