# original-repo/.github/workflows/on-push-sync.yml

name: Trigger Fork Sync via Common Actions

on:
  push:
    branches:
      - master

jobs:
  call-common-sync:
    uses: vaibhhvv/common-actions/.github/workflows/trigger-fork-sync-v2.yml@main
    with:
      source_repo: vaibhhvv/original-repo-3
      source_branch: master
      fork_repo: vaibhshah/forked-repo-3
      target_branch: master
    secrets:
      PAT: ${{ secrets.PAT }}
