name: Sync from upstream

on:
  repository_dispatch:
    types: [sync-upstream]

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      SOURCE_REPO: vaibhhvv/original-repo-3
      SOURCE_BRANCH: master
      TARGET_BRANCH: master

    steps:
      # Checkout fork repo (this repo)
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important to preserve history

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/${{ env.SOURCE_REPO }}.git
          git fetch upstream ${{ env.SOURCE_BRANCH }}

      - name: Preserve workflows
        run: |
          git checkout ${{ env.TARGET_BRANCH }} -- .github/workflows || true

      - name: Rebase from upstream
        run: |
          git checkout -B sync-fork
          git rebase upstream/${{ env.SOURCE_BRANCH }}

          # Restore workflows
          git checkout HEAD -- .github/workflows || true

      - name: Commit changes if any
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "🔄 Sync from upstream ${{ env.SOURCE_REPO }}"

      # ✅ Must run inside a checked-out Git repo
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "🔄 Sync from upstream"
          title: "🔄 Sync from upstream"
          body: Auto-generated PR to sync with upstream `${{ env.SOURCE_REPO }}`
          base: ${{ env.TARGET_BRANCH }}
          branch: sync-fork
