name: Sync Forked Repo

on:
  repository_dispatch:
    types: [sync-fork]

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      SOURCE_REPO: vaibhhvv/original-repo-3
      FORK_REPO: vaibhshah/forked-repo-3
      BRANCH: master

    steps:
      - name: Clone forked repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/${FORK_REPO}.git fork-repo
          cd fork-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch and merge upstream
        run: |
          cd fork-repo
          git remote add upstream https://github.com/${SOURCE_REPO}.git
          git fetch upstream $BRANCH
          git checkout -B sync-fork origin/$BRANCH

          # Save fork workflows
          git checkout origin/$BRANCH -- .github/workflows || true

          # Reset to upstream/master
          git reset --hard upstream/$BRANCH

          # Restore fork workflows
          git checkout sync-fork -- .github/workflows || true

          git add .
          if git diff --cached --quiet; then
            echo "No changes to sync."
            exit 0
          fi

          git commit -m "🔄 Sync from upstream"
          git push -f origin sync-fork

      - name: Create PR using GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          cd fork-repo
          gh pr create \
            --title "🔄 Sync from upstream" \
            --body "Auto-generated PR to sync with upstream \`${SOURCE_REPO}\`" \
            --base $BRANCH \
            --head sync-fork
