name: Sync from upstream

on:
  repository_dispatch:
    types: [sync-from-upstream]

permissions:
  contents: write

env:
  UPSTREAM_REPO: vaibhhvv/original-repo-3
  FORK_BRANCH: master
  SYNC_BRANCH: sync-upstream-branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout forked repo's master branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.FORK_BRANCH }}
          token: ${{ secrets.PAT }}

      - name: Add upstream remote
        run: git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git

      - name: Fetch upstream master
        run: git fetch upstream master

      - name: Create sync branch from fork master
        run: git checkout -b $SYNC_BRANCH

      - name: Merge upstream master into sync branch, preserving fork workflows folder
        run: |
          # Save workflows folder
          mkdir -p ../safe-workflows
          mv .github/workflows ../safe-workflows/

          # Merge upstream/master with ours strategy (keeps current files as-is, but records merge)
          git merge -s ours upstream/master -m "Preserve fork workflows folder" --allow-unrelated-histories

          # Restore workflows folder
          mv ../safe-workflows/workflows .github/

          # Checkout upstream files (except workflows folder)
          git checkout upstream/master -- .

          # Restore workflows folder to original fork version (HEAD)
          git checkout HEAD -- .github/workflows

          # Stage all changes
          git add .


      - name: Check if there are changes to commit
        id: git_diff
        run: |
          if git diff --cached --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes if any
        if: steps.git_diff.outputs.changes == 'true'
        run: |
          git commit -m "🔄 Sync fork with upstream: ${{ env.UPSTREAM_REPO }}:${{ env.FORK_BRANCH }} 🤖"
          git push -u origin $SYNC_BRANCH --force

      - name: Create or update Pull Request
        if: steps.git_diff.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: "🔄 Sync fork with upstream: ${{ env.UPSTREAM_REPO }}:${{ env.FORK_BRANCH }} 🤖"
          title: "Sync fork with upstream"
          body: |
            This PR syncs changes from the upstream repository `{{ env.UPSTREAM_REPO }}` branch `${{ env.FORK_BRANCH }}`.

            The `.github/workflows` folder remains untouched.
          head: $SYNC_BRANCH
          base: ${{ env.FORK_BRANCH }}
          draft: false
