name: Sync from upstream

on:
  repository_dispatch:
    types: [sync-from-upstream]

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      SOURCE_REPO: vaibhhvv/original-repo-3
      SOURCE_BRANCH: master
      TARGET_BRANCH: master

    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.TARGET_BRANCH }}

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/${{ env.SOURCE_REPO }}.git
          git fetch upstream ${{ env.SOURCE_BRANCH }}

      - name: Save workflows from fork
        run: |
          mkdir -p ../preserved-workflows
          cp -r .github/workflows ../preserved-workflows || true

      - name: Sync from upstream (preserving workflows)
        run: |
          git checkout -B sync-fork origin/${{ env.TARGET_BRANCH }}
          git merge --no-commit upstream/${{ env.SOURCE_BRANCH }} || true

          # Remove any accidentally staged workflows
          git reset .github/workflows || true
          rm -rf .github/workflows

          # Only add changes outside workflows
          git add -A
          git reset .github/workflows || true

          # Skip if no other changes exist
          if git diff --cached --quiet; then
            echo "No changes to sync"
            exit 0
          fi

          git commit -m "🔄 Sync from upstream ${{ env.SOURCE_REPO }}"


      - name: Push sync branch
        run: |
          git push -f origin sync-fork

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "🔄 Sync from upstream"
          title: "🔄 Sync from upstream"
          body: |
            Auto-generated PR to sync with upstream `${{ env.SOURCE_REPO }}`
          base: ${{ env.TARGET_BRANCH }}
          branch: sync-fork

