name: Trigger Fork Sync

on:
  push:
    branches:
      - master      # or 'develop' if you're doing this in original-repo-2
    # Ignore changes ONLY inside the .github/workflows folder
    paths-ignore:
      - '.github/workflows/**'

jobs:
  Trigger-Fork-Sync:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger fork sync via repository_dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: vaibhhvv/forked-repo-1
          event-type: Trigger-Fork-Sync
